name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  # roda todo dia meia-noite
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Gerar Snake (com privados)
        uses: Platane/snk@v3
        with:
          github_user_name: ELLEN2121
          outputs: dist/github-contribution-grid-snake.svg
        env:
          GITHUB_TOKEN: ${{ secrets.SNAKE_TOKEN }}   # 👈 usa o seu PAT

      - name: Publicar no branch output
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
